config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  devise_for :users
  resources :users
  resources :events do
		resources :charges
  	resources :attendances
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :event
	belongs_to :user
	
	after_create :new_attendance_send

  def new_attendance_send
    AttendanceMailer.new_attendance_email(self).deliver_now
		AttendanceMailer.new_attendance_creator_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	has_many :attendances
	has_many :users, through: :attendances
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true
	validates :location, presence: true
	validate :duration_mutliple_of_5
	validate :is_already_passed

	def is_already_passed
		@startdate = self.start_date
		if @startdate != nil
			errors.add(:startdate, "Ne doit pas être déjà passé") unless @startdate > Time.now
		else
			errors.add(:startdate, "Doit être rempli")
		end
	end

	def duration_mutliple_of_5
		@duration = self.duration
		if @duration != nil
			errors.add(:duration, "Doit être un multiple de 5") unless @duration % 5 == 0
		else
			errors.add(:duration, "Doit être rempli")
		end
	end

	def end_date
		end_date = Time.at(self.start_date.to_i + (self.duration * 60))
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  after_create :welcome_send

	has_many :attendances
  has_many :events
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
  include EventsHelper
  include UsersHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	
	before_action :authenticate_user!

	def create
		a = Attendance.new(event_id: params[:event_id], user_id: current_user.id, stripe_customer_id: params[:customer_id])

		if a.save

			@amount = Event.find(params[:event_id]).price * 100

			customer = Stripe::Customer.create(
    		:email => params[:stripeEmail],
    		:source  => params[:stripeToken]
  		)

  		charge = Stripe::Charge.create(
    		:customer    => customer.id,
    		:amount      => @amount,
    		:description => 'Rails Stripe customer',
    		:currency    => 'usd'
  		)

			redirect_to event_path(params[:event_id])
			flash[:success] = "Nous avons enregistré votre inscription à #{Event.find(params[:event_id]).title}.\n Un mail de confirmation a été envoyé à #{current_user.email}"
		else
			flash[:danger] = "Un problème est survenu"
			render :new
		end
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
	def new
    @event = Event.find(params[:event_id])
    @attendance = nil
    @attendance = Attendance.find_by(event_id: @event.id, user_id: current_user.id)
	end  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	
	def index
		@events = Event.all
	end



	def new
		@event = Event.new
	end



	def edit
		@event = Event.find(params[:id])
		check_access_authorization(@event.user)
	end



	def create
		@event = Event.new(title: params[:title], description: params[:description], user: current_user, start_date: params[:start_date], location: params[:location], duration: params[:duration], price: params[:price])

		puts params

		if @event.errors.any?
			render :new
		end
		if @event.save
			redirect_to root_path
			flash[:success] = "#{@event.title} a bien été créé."
		else
			flash[:danger] = "Un problème est survenu."
			render :new
		end
	end



	def update
		@event = Event.find(params[:id])
		check_access_authorization(@event.user)

		if @event.update(title: params[:title], description: params[:description], start_date: params[:start_date], duration: params[:duration], location: params[:location], price: params[:price])
			redirect_to events_path(@event.id)
			flash[:success] = "#{@event.title} a bien été mis à jour."
		else
			render :edit
			flash[:danger] = "Un problème est survenu."
		end
	end



	def destroy
		@event = Event.find(params[:id])
		check_access_authorization(@event.user)
		event_title = @event.title
		if @event.destroy
			redirect_to root_path
			flash[:success] = "#{event_title} a bien été supprimé."
		end
	end


	
	def show
		@event = Event.find(params[:id])
		@creator = @event.user
		@participants = @event.users
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
	def show
		@user = User.find(params[:id])
    @events = @user.events

    redirect_to user_path(current_user.id) unless current_user == @user
	end



	def edit
		@user = User.find(current_user.id)
	end



	def update
		@user = User.find(current_user.id)

		if @user.update(first_name: params[:first_name], last_name: params[:last_name], description: params[:description])
			redirect_to user_path(@user.id)
			flash[:success] = "Votre profil a bien été mis à jour."
		else
			render :edit
			flash[:danger] = "Un problème est survenu."
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def check_access_authorization(user)
    unless is_current_user?(user)
      redirect_to root_path
      flash[:danger] = "Accès non-autorisé"
    end
  end
  def is_current_user?(user)
  	current_user == user
  end
  def class_for_flash(type)
  case type
    when 'notice' then "info"
    when 'success' then "success"
    when 'danger' then "danger"
    when 'alert' then "warning"
  end
end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def is_not_linked_to?(creator)
		current_user != creator && check_attendant_user != true
	end

	def check_attendant_user
  	@participants.each do |participant|
  		if participant == current_user
  			return true
  		end
  	end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<% if @attendance == nil %>

<%= form_tag event_attendances_path, method: 'post' do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: €<%= @event.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @event.price*100 %>"
          data-locale="auto"></script>
<% end %>

<% else %>
<p>Tu es déjà inscrit</p>
<%= link_to 'Accueil', root_path %>
<% end %>

app/views/events/_event-card.html.erb
<div class="col-3">
		<div class="card">
			<div class="card-header">
				<%= link_to "#{event.title}", event_path(event.id), class: "card-title"%>	
			</div>
			<div class="card-body">
				<p class="card-text"><%= event.description %></p>
			</div>
		</div>
	</div>

app/views/events/edit.html.erb
<h1>Modifier ton évènement :</h1>

<%= form_tag(event_path(@event.id), method: 'patch') do %>
<%= label_tag('title', 'Titre', class:"") %>
<%= text_field_tag('title', @event.title, class:"") %>
<%= label_tag('description', 'Description', class:"") %>
<%= text_area_tag('description', @event.description, class:"") %>
<%= label_tag('price', 'Prix', class:"") %>
<%= text_field_tag('price', @event.price, class:"") %>
<%= label_tag('location', 'Lieu', class:"") %>
<%= text_field_tag('location', @event.location, class:"") %>
<%= label_tag('event', 'Date de début', class:"") %>
<%= datetime_field_tag("start_date", @event.start_date) %>
<%= label_tag('duration', 'Durée', class:"") %>
<%= text_field_tag('duration', @event.duration, class:"") %>

<%= submit_tag('Editer', class:"") %>
<% end %>
<%= button_to "Supprimer", event_path(@event), data: {confirm: 'Es-tu sûr(e) ?'}, method: :delete %>

<% if @event.errors.any? %>
  <div class="alert warning" role="alert">
    <p>Nous navons pas réussi à modifier l'event pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <p>Merci de réessayer</p>
  </div>
<% end %>

app/views/events/index.html.erb
<h1 class="w-100 d-flex f-middle">Voici tous les évenements passé et à venir ! :</h1>


<div class="grid">
	<% @events.each do |event| %>
	<%= render "event-card", locals = {event: event} %>
	<% end %>
</div>

app/views/events/new.html.erb
<h1>Nouvel event</h1>

<%= form_tag(events_path, method: 'post', id: "new_event", class:"") do %>
<%= label_tag('title', 'Titre', class:"") %>
<%= text_field_tag('title', nil, class:"") %>
<%= label_tag('description', 'Description', class:"") %>
<%= text_area_tag('description', nil, class:"") %>
<%= label_tag('price', 'Prix', class:"") %>
<%= text_field_tag('price', nil, class:"") %>
<%= label_tag('location', 'Lieu', class:"") %>
<%= text_field_tag('location', nil, class:"") %>
<%= label_tag('start_date', 'Date de début', class:"") %>
<%= datetime_field_tag('start_date', '20/02/2019 00:00', class:"") %>
<%= label_tag('duration', 'Durée', class:"") %>
<%= text_field_tag('duration', 0, class:"") %>

<%= submit_tag('Créer', class:"") %>
<% end -%>

<% if @event.errors.any? %>
  <div class="alert alert-warning mt-2" role="alert">
    <p>Nous navons pas réussi à créer d'event pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <p>Merci de réessayer</p>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p>Créé par <%= "#{@creator.first_name} #{@creator.last_name}" %></p>
<p><%= @event.description %></p>
<p><em>Nombre d'inscrit : <%= @participants.count %></em></p>
<p>Commence le : <%= @event.start_date %></p>
<p>Finis le : <%= @event.end_date %></p>
<p><%= @event.location %></p>
<p>Prix : <%= @event.price %> €</p>

<% if is_not_linked_to?(@creator) %>
<%= link_to "S'inscrire", new_event_charge_path(@event.id), class:"" %>
<% elsif  current_user == @creator %>
<%= link_to "Gestion de l'évènement", edit_event_path(@event.id), class:"" %>
<% end -%>

app/views/layouts/_footer.html.erb
<h5>Made with love</h5>

app/views/layouts/_header.html.erb
	<nav class="navbar">
		<div class="d-flex f-middle">	
      <%= link_to "Accueil", root_path, class:'navbar-brand' %>
      <ul class="d-flex f-middle nav-list">
        <li class="nav-item"><%= link_to "Créer un event", new_event_path, class:"nav-link" %></li>
      </ul>
    </div>
    <div>  
      <div class="dropdown f-right-item">
        <button class="dropdown-toggler btn btn-secondary">User</button>
        <div class="dropdown-menu secondary f-middle f-column">
          <% if user_signed_in? %>
          <%= link_to "Profil", user_path(current_user.id), class:"dropdown-item" %>
          <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
          <% else %>
          <%= link_to "Connexion", new_user_session_path, class:"dropdown-item" %>
          <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CorrectionVideo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <header class="light">
        <%= render "layouts/header" %>
      </header>
      <% flash.each do |type, value| %>
        <div class="alert <%= class_for_flash(type) %> text-white d-flex f-middle">
          <h5 class="text-white"><%= value %></h5>
        </div>
      <% end %>
      <main>
        <%= yield %>
      </main>
      <footer class="light d-flex f-middle">
        <%= render "layouts/footer" %>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_event-card.html.erb
<div class="col-3">
		<div class="card">
			<div class="card-header">
				<%= link_to "#{event.title}", event_path(event.id), class: "card-title"%>	
			</div>
			<div class="card-body">
				<p class="card-text"><%= event.description %></p>
			</div>
		</div>
	</div>

app/views/users/edit.html.erb
<h1>Modifier ton profil :</h1>

<%= form_tag(user_path(@user.id), method: 'patch') do %>
<%= label_tag('first_name', 'Prénom', class:"") %>
<%= text_field_tag('first_name', @user.first_name, class:"") %>
<%= label_tag('last_name', 'Nom', class:"") %>
<%= text_field_tag('last_name', @user.last_name, class:"") %>
<%= label_tag('description', 'Description', class:"") %>
<%= text_area_tag('description', @user.description, class:"") %>


<%= submit_tag('Editer', class:"") %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Ton profil :</h1>

<p>Prénom : <%= @user.first_name %></p>
<p>Nom : <%= @user.last_name %></p>
<p>Email : <%= @user.email %></p>
<p>Description : <%= @user.description %></p>
<div class="d-flex f-middle">
<%= link_to "Editer les informations personnelles", edit_user_registration_path(@user.id), class:"btn btn-info" %>
<%= link_to "Editer le profil", edit_user_path(@user.id), class:"btn btn-info" %>
</div>

<h2>Tout tes évènements :</h2>

<div class="grid">
	<% @events.each do |event| %>
	<%= render "events/event-card", locals = {event: event} %>
	<% end %>
</div>